name: Build Halium pro Pixel 6

on:
  workflow_dispatch: # Spuštění ručně tlačítkem

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Instalace vývojářských nástrojů a ARM kompilátorů
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential cpio curl flex git kmod libssl-dev libtinfo5 python3 libncurses5-dev git-lfs jq libxml2-utils rsync gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Stažení zdrojového kódu kernelu Pixel 6
        run: |
          # Použijeme stabilnější větev lineage-21 (Android 14) pro Pixel 6
          git clone --depth=1 -b lineage-21 https://github.com/LineageOS/android_kernel_google_gs101 kernel

      - name: Stažení Halium nástrojů
        run: |
          git clone --depth=1 -b halium-11.0 https://github.com halium-boot

      - name: Kompilace samostatného Linuxového Jádra
        run: |
          cd kernel
          
          # Nastavení prostředí pro křížovou kompilaci na ARM64
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          echo "Konfiguruji kernel pro Pixel 6..."
          # LineageOS používá pro Google Tensor (Pixel 6) konfiguraci gki_defconfig
          make gki_defconfig
          
          echo "Spouštím samotnou kompilaci jádra..."
          # Spustíme samotný build čistého linuxového jádra
          make -j$(nproc) Image.lz4
