nname: Konecne funkcni build Pixel 6

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Priprava systemu
        run: sudo apt-get update && sudo apt-get install -y bc bison build-essential cpio curl flex git kmod libssl-dev libtinfo5 python3 libncurses5-dev git-lfs jq libxml2-utils rsync clang lld llvm libssl-dev gcc-aarch64-linux-gnu libelf-dev dwarves

      - name: Vytvoreni SWAP pameti v cloudu proti Error 137
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 12

      - name: Stahování zdrojových kódů pres GitHub Checkout
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_kernel_google_gs101
          ref: lineage-20
          path: kernel

      - name: Konfigurace a stavba jadra
        run: |
          cd kernel
          
          # Nastavení prostředí
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export LLVM=1
          export CC=clang
          export LD=ld.lld
          export AR=llvm-ar
          export NM=llvm-nm
          export OBJCOPY=llvm-objcopy
          export OBJDUMP=llvm-objdump
          export STRIP=llvm-strip
          
          echo "Konfiguruji architekturu Google Tensor..."
          make gki_defconfig
          
          echo "Vypinam LTO pres konfiguracní parametry..."
          sed -i 's/CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_NONE=y/' .config
          sed -i 's/CONFIG_LTO_CLANG_THIN=y/CONFIG_LTO_NONE=y/' .config
          sed -i '/CONFIG_LTO_CLANG/d' .config
          echo "CONFIG_LTO_NONE=y" >> .config
          
          echo "Vypinam CONFIG_DEBUG_INFO_BTF pro preskoceni pahole chyb..."
          sed -i 's/CONFIG_DEBUG_INFO_BTF=y/CONFIG_DEBUG_INFO_BTF=n/' .config
          sed -i '/CONFIG_DEBUG_INFO_BTF/d' .config
          echo "CONFIG_DEBUG_INFO_BTF=n" >> .config
          
          # Potvrzení změn v konfiguraci
          make olddefconfig
          
          echo "Spouštím bezpečnou kompilaci jádra..."
          make -j2 Image

      - name: Nahrání zkompilovaného jádra ke stažení
        uses: actions/upload-artifact@v4
        with:
          name: Pixel6-Linux-Kernel
          path: kernel/arch/arm64/boot/Image
