name: Konecne funkcni build Pixel 6

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Priprava systemu
        run: sudo apt-get update && sudo apt-get install -y bc bison build-essential cpio curl flex git kmod libssl-dev libtinfo5 python3 libncurses5-dev git-lfs jq libxml2-utils rsync clang lld llvm libssl-dev gcc-aarch64-linux-gnu libelf-dev

      - name: Stahování zdrojových kódů pres GitHub Checkout
        uses: actions/checkout@v4
        with:
          repository: LineageOS/android_kernel_google_gs101
          ref: lineage-20
          path: kernel

      - name: Konfigurace a stavba jadra
        run: |
          cd kernel
          
          # Kompletní nastavení LLVM nástrojů
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export LLVM=1
          export CC=clang
          export LD=ld.lld
          export AR=llvm-ar
          export NM=llvm-nm
          export OBJCOPY=llvm-objcopy
          export OBJDUMP=llvm-objdump
          export STRIP=llvm-strip
          
          echo "Konfiguruji architekturu Google Tensor..."
          make gki_defconfig
          
          echo "Spouštím hlavní kompilaci jádra..."
          make -j$(nproc) Image

      - name: Nahrání zkompilovaného jádra ke stažení
        uses: actions/upload-artifact@v4
        with:
          name: Pixel6-Linux-Kernel
          path: kernel/arch/arm64/boot/Image
